manifest.php
model/MediaService.php
scripts/update/Updater.php

- UDI-157 fix(media): use a correct `taoRevision` repository reference in `MediaService` when registering a new media file upload
- UDI-157 chore(version): bump

UDI-157: Media files don't get uploaded when `taoRevision` is enabled

---

model/MediaSource.php
test/integration/model/MediaSourceTest.php

Remove media prefix from link to allow FE retrieve media on shared stimulus authoring

Remove media prefix from link to allow FE retrieve media

---

manifest.php
views/js/previewer/adapter/item/qtiSharedStimulusItem.js

Related to: https://oat-sa.atlassian.net/browse/NEX-1215
Remove dependency `taoColorContrast`, 
insted 
`taoColorContrast/runner/plugins/tools/itemThemeSwitcher`
use 
`taoQtiTest/runner/plugins/tools/itemThemeSwitcher/itemThemeSwitcher`
In case not installed `taoColorContrast` contrast plugin will not present
In case installed `taoColorContrast` contrast plugin will work

Fix NEX-1215 use plugin itemThemeSwitcher from taoQtiTest

---

manifest.php
model/sharedStimulus/parser/SharedStimulusMediaParser.php
test/unit/model/sharedStimulus/parser/SharedStimulusMediaParserTest.php

Problem.
When importing item with shared stimulus which contains video the import fails.
To test use item found on [TAO-10460](https://oat-sa.atlassian.net/browse/TAO-10460)

Add possibility to process encoded video on shared stimulus embedded assets

---

manifest.php
test/unit/model/sharedStimulus/parser/SharedStimulusMediaParserTest.php

Fixing broken unit test in `SharedStimulusMediaParserTest`:
this PR changes a valid XML string to **invalid** to raise exception in SUT to cover expected scenario of invalid input.

Fix broken unit test in SharedStimulusMediaParserTest

---

manifest.php
model/MediaSource.php

Measures to improve https://oat-sa.atlassian.net/browse/CON-111
Sample request `http://depp-authoring.docker.localhost/taoItems/ItemContent/files?path=taomedia%3A%2F%2Fmediamanager%2F&uri=https%3A%2F%2Fdepp-auth.taocloud.org%2Ftao.rdf%23i16049178955445394934&lang=en-US&filters=video%2Fmp4%2Cvideo%2Favi%2Cvideo%2Fogv%2Cvideo%2Fmpeg%2Cvideo%2Fogg%2Cvideo%2Fquicktime%2Cvideo%2Fwebm%2Cvideo%2Fx-ms-wmv%2Cvideo%2Fx-flv%2Caudio%2Fmp3%2Caudio%2Fvnd.wav%2Caudio%2Fogg%2Caudio%2Fvorbis%2Caudio%2Fwebm%2Caudio%2Fmpeg%2Capplication%2Fogg%2Caudio%2Faac%2Caudio%2Fwav%2Caudio%2Fflac` 
Tested  with `5372` media files in library
before change  - `26711` queries 
after change - `2952` queries

Reduced queries count to RDS while building media tree

---

test/integration/model/SharedStimulusPackageImporterTest.php

This fix issue with unzipping file from git under MacOS.
Issue was found by @bartlomiejmarszal testing locally the deployment PR: https://github.com/oat-sa/udir-deploy/pull/66

fix: remove sample data with tricky name caused issues for developers on MacOS

---

views/js/qtiCreator/editor/interactionsPanel.js

Possible hotfix for https://oat-sa.atlassian.net/browse/AUT-767
There is more enhanced way to fix it (actually remove translation for id). It would be more stable in long-term, but might bring regressions in short-term. So if possible, I'd go with this hotfix for now and create a tech-debt ticket to remove translation from id.

fix: remove on/off sections toggling in passage authoring

---

views/js/controller/editInstance.js
views/js/previewer/component/qtiSharedStimulusItem.js
views/js/previewer/proxy/qtiSharedStimulusItem.js

Related to: https://oat-sa.atlassian.net/browse/AUT-738
Added passage custom styles to dummy itemData in `getItem` function of `proxy/qtiSharedStimulusItem`
How to test:
- create new passage
- add custom styles
- save and go to Assets page
- refresh page and see passage preview

feat/AUT-738/ preview passage in Assets

---

views/js/richPassage/xincludeRendererAddStyles.js

Related to: https://oat-sa.atlassian.net/browse/AUT-34
Update `xincludeRendererAddStyles`, now it can be used in iframe
How to test:
- create rich passage
- go to item Authoring
- try add passage in items, check preview in resource manager
Need to run `php ./tao/scripts/taoUpdate.php`

feat/AUT-34/ xincludeRendererAddStyles can be used in iframe

---

composer.json
migrations/Version202108271508361888_taoMediaManager.php
model/classes/user/TaoAssetRoles.php
model/mapper/MediaSourcePermissionsMapper.php
test/unit/model/mapper/MediaSourcePermissionsMapperTest.php

**Relates to:** _[ADF-627](https://oat-sa.atlassian.net/browse/ADF-627)_
---
**Changes:**
* `files`, `upload` and `delete` permissions revoked;
* `viewAsset` permission added;
* Check for `viewAsset` read access during permissions mapper.
---
**Companion PRs:**
* https://github.com/oat-sa/extension-tao-item/pull/512
* https://github.com/oat-sa/tao-core/pull/3085

Fix/ADF-627/Reconfigure Asset Content Creator role permissions

---

views/cypress/tests/assets-page.spec.js
views/cypress/tests/assets.spec.js

Related to: https://oat-sa.atlassian.net/browse/AUT-1034
We have explicitly defined a specific time for most of our request interception/waiting. 
i.e: .wait('@editItem', { requestTimeout: 10000 }) 
We should make this requestTimeout of 10000ms the norm by defining it as a default in cypress.json and removing each explicit mention of it in our .wait() function calls.
**How to test:**
Run cypress and check that updated tests pass without errors after updating default request timeout.

AUT-1034 move requestTimeout to cypress.json configs

---

views/cypress/tests/assets.spec.js

Related to: https://oat-sa.atlassian.net/browse/AUT-963
Dependency:
Move wait.("@treeRender") to commands
How to test:
run test `taoMediaManager/views/cypress/tests/assets.spec.js`

fix/AUT-963/ e2e move treeRender in commands

---

views/js/qtiCreator/editor/interactionsPanel.js

Related to Issue: https://oat-sa.atlassian.net/browse/AUT-773
Related to PR:  https://github.com/oat-sa/extension-tao-itemqti/pull/1899
id attributes get translated. Check that rich passage (Media manager) interaction panel works as expected.
SETPS to test:
• Checkout to branch: fix/AUT-773/id-attributes-get-translated
•Create a rich passage
•Interaction panel on the left should contain an inline text interaction as expected.
• Inspect elements in the dev tools: Group id shouldn't change independently of the language
ENV to test: http://test-silvia.playground.kitchen.it.taocloud.org:41441

fix: interaction panel in rich passage

---

views/cypress/tests/assets.spec.js
views/cypress/utils/selectors.js

**End to end testing.**
Related to: https://oat-sa.atlassian.net/browse/AUT-1167
**Description of changes:**
Creation of E2E tests for passage authoring. Open passage authoring:
Tests for:
-  Asset creation
-  Click authoring, 
-  Check all blocks present, 
-  Go back (check that asset present)
-  Delete asset
**How to run locally:**
Checkout to AUT-1167/e2e-testing-open-passage-authoring in extn taoMediaManager
run tests from tao core extn:
npm run cy:open - to run in browser
or npm run cy:run - for headless execution
**Expected result:** All tests pass successfully

feature: [e2e testing] add open passage authoring tests

---

views/js/qtiCreator/editor/propertiesPanel.js

Related to: https://oat-sa.atlassian.net/browse/AUT-1331
We need to define/import `jquery` in each file where `jquery` is used
In case it is not defined will be loaded `jquery` from `tao/views/js` not from bundles

fix: define jquery when it is used

---

views/cypress/tests/assets-authoring-ckeditor.spec.js
views/cypress/tests/assets.spec.js
views/cypress/utils/add-A-block-interaction-asset.js
views/cypress/utils/selectors.js

Related to: https://oat-sa.atlassian.net/browse/AUT-1169
Depends https://github.com/oat-sa/tao-core/pull/3230
1. Added new test for CKeditor `views/cypress/tests/assets-authoring-ckeditor.spec.js`
2. Stabilised old tests
How to test:
1. remove temporary delivery tests `ltiDeliveryProvider/views/cypress` `taoQtiTest/views/cypress/test/delivery` or exclude them
2. `cd tao/views`
3. `npm run cy:run`

fix: check ckeditor in A-block

---

model/sharedStimulus/service/PatchService.php
model/sharedStimulus/service/StoreService.php
test/integration/model/SharedStimulusImporterTest.php

This ticket is intended to fix the issue: https://oat-sa.atlassian.net/browse/AUT-1538
The issue happens when an item is imported with a passage which has not stylesheet. The solution proposed is to do not return an an error for this case. 
During the authoring of these imported passages, we were not able to author it because of for some reason, the expected language is not a resource, but a literal one. I just converted to a resource in cause of this issue happens.

[AUT-1538] Fixed failed to import passage with no stylesheet

---

views/cypress/tests/add-asset-passage-to-interaction.spec.js
views/cypress/utils/check-read-only.js
views/cypress/utils/import-selected-asset.js
views/cypress/utils/resource-manager.js
views/cypress/utils/selectors.js

**End to end testing.**
Related to: https://oat-sa.atlassian.net/browse/AUT-1195
Depends on :
- https://github.com/oat-sa/extension-tao-itemqti/pull/1960
- https://github.com/oat-sa/tao-core/pull/3250
**Description of changes:**
Creation of E2E tests for: Creating and importing passages/asset and adding to prompt and choice of interaction
**How to run locally:**
Checkout to branch  `feature/AUT-1195/e2e-add-asset-passage-to-interaction`
in extensions:
- https://github.com/oat-sa/tao-core
- https://github.com/oat-sa/extension-tao-itemqti
- https://github.com/oat-sa/extension-tao-mediamanager
**run tests from tao core extn:**
npm run[ cy:open](url) - to run in browser
or npm run` cy:run` - for headless execution
File to test: `add-asset-passage-to-interaction.spec.js`
All tests should pass:

Feature/aut 1195/e2e add asset passage to interaction

---

scripts/ReplaceSharedStimulusMedia.php

In order to fix [rich passage authoring bug](https://oat-sa.atlassian.net/browse/AUT-1620) we need to run this script on the environment.
As discussed we going to test it on some env and then include it as a migration.
Short how-to use document: https://oat-sa.atlassian.net/wiki/spaces/~437715569/pages/1709211880/AUT-1620+Fix+passages+created+before+rich+passage+authoring+was+implemented

hotfix -  script migrating old passages to store in sub directory

---

views/js/controller/actions.js

**Description**
Fix warning message when try to delete an asset used in item or passage.
The bug is not showing list of items in warning popup
**Ticket**
https://oat-sa.atlassian.net/browse/REL-612

fix: add missing items variable

---

migrations/Version202112230835581888_taoMediaManager.php

The time necessary to complete `ReplaceSharedStimulusMedia` depends on the amount of shared stimulus passages, and should be considered as a long running migration. Such migrations should be executed manually.
Related to : https://oat-sa.atlassian.net/browse/REL-709
- execute `php index.php '\oat\tao\scripts\tools\Migrations' -c execute -v 'oat\taoMediaManager\migrations\Version202112230835581888_taoMediaManager'`
- verify that migration informs about the script, instead of running it

fix: inform about, rather than execute long running script

---

model/classes/ServiceProvider/MediaServiceProvider.php

**Associated Jira issue:**  [ADF-1148](https://oat-sa.atlassian.net/browse/ADF-1148)
- Release branch created out of v12.29.0 tag: https://github.com/oat-sa/extension-tao-mediamanager/compare/v12.29.0...release-12.29.0
- Branch being merged just contains changes for copiers: https://github.com/oat-sa/extension-tao-mediamanager/compare/release-12.29.0...fix/ADF-1148-setup-copiers-using-tags

fix: Register copiers in the DI container using tags

---

views/js/qtiCreator/component/tpl/sharedStimulusAuthoring.tpl
views/js/qtiCreator/editor/styleEditor/colorSelector.js
views/js/qtiCreator/editor/styleEditor/fontSizeChanger.js

**RELATED TO:**
AUT: 2639 [https://oat-sa.atlassian.net/browse/AUT-2639](url)
AUT-2653 [https://oat-sa.atlassian.net/browse/AUT-2653](url)
AUT-2654 [https://oat-sa.atlassian.net/browse/AUT-2654](url)
**STEPS TO TEST:**
1. Create  Passage add texto and an image
2. change the background color, or any other colors in color picker
3. Click on image
**CURRENT RESULT:**
- Background color doesn't apply to all background but seems broken
- When image active, bin button inherits styles: background color and padding, resutling on a bigger size.
**EXPECTED RESULT:**
- Background color is uniform and affect all text  background.
- When focusing on image, bin icon stays standard color and size

fix: remove * from data-target so styles don't get to children elements

---

views/js/richPassage/helpers.js

Related to :[ AUT-2560](https://oat-sa.atlassian.net/browse/AUT-2560)
According feature Scope passage style in Solar UI https://github.com/oat-sa/tao-deliver-fe/pull/521 need to add 
- a `stylesheets` property added to the x-include declaration, with a mapping between the serial and the CSS file
- a couple of properties `includeHref` and `includeSerial` added to the stylesheet declaration, referencing the passage

feat: support new ui test preview

---

model/sharedStimulus/service/CopyService.php
test/unit/model/sharedStimulus/service/CopyServiceTest.php

[AUT-2687](https://oat-sa.atlassian.net/browse/AUT-2687)
[ADF-1097](https://oat-sa.atlassian.net/browse/ADF-1097)
[ADF-1087](https://oat-sa.atlassian.net/browse/ADF-1087)
[ADF-1105](https://oat-sa.atlassian.net/browse/ADF-1105)
* Use `children` sublist to get all necessary CSS files
* Use `name` list-value to get the basename
This change is needed because of a previous change in the return value format of `ListStylesheetsService::getList()` ([here](https://github.com/oat-sa/extension-tao-mediamanager/blob/develop/model/sharedStimulus/css/service/ListStylesheetsService.php#L31))

[Fix] Use children list from css files in accordance with the latest changes

---

views/js/previewer/proxy/qtiSharedStimulusItem.js
views/js/qtiCreator/component/tpl/sharedStimulusAuthoring.tpl
views/js/qtiCreator/editor/styleEditor/colorSelector.js
views/js/qtiCreator/editor/styleEditor/fontSelector.js
views/js/qtiCreator/editor/styleEditor/fontSizeChanger.js
views/js/qtiCreator/editor/styleEditor/styleEditor.js
views/js/qtiCreator/helper/formatStyles.js
views/js/qtiCreator/helper/sharedStimulusLoader.js
views/js/richPassage/helpers.js
views/js/richPassage/xincludeRendererAddStyles.js

**Related to:** 
[AUT-2725](https://oat-sa.atlassian.net/browse/AUT-2725)
[TR-4800](https://oat-sa.atlassian.net/browse/TR-4800)
**Description:**
- Remove Asset mainClass for the `tao-user-styles`
- Apply CSS format to `tao-user-styles`
- Hide CSS styles from when there is no content on the Asset
**How to check:**
- Create an Asset with no data. Save it. Upload a CSS file. Go out and edit again. Check the CSS is not applied to the Asset.
- Create an Asset with CSS files and Passage styles. Import on Item and create test. Check Previews and solar Delivery.

Fix/aut 2694/hide styles with no class name

---

views/js/qtiCreator/editor/styleEditor/styleEditor.js

Related to: https://oat-sa.atlassian.net/browse/AUT-2637
Fix old passages on save. To have styles in item and tests preview, delivery

fix: remove mainClass from old selectors

---

views/js/qtiCreator/editor/styleEditor/styleEditor.js

Related to https://github.com/oat-sa/extension-tao-mediamanager/pull/441
Remove extra space on the replace action to avoid keeping 2 blank spaces.

fix: remove extra space on remove the mainClass

---

views/js/qtiCreator/editor/ckEditor/htmlEditor.js

Related to: https://oat-sa.atlassian.net/browse/TAO-10644
Regression after https://github.com/oat-sa/extension-tao-itemqti/pull/2170/files#diff-8812e9f82994923534c4ea77dfd8c8c3637d071f859a5eaa6ef02baae2c51664
Here we expecting Promise https://github.com/oat-sa/extension-tao-itemqti/blob/d7ec12874281dadaf19e2fed43867af6ecb93a5e/views/js/qtiCreator/widgets/static/tooltip/components/editorField.js#L66-L92

fix: return promise, used in tooltip

---

composer.json
model/classes/Copier/AssetClassCopier.php
model/classes/ServiceProvider/MediaServiceProvider.php
test/unit/model/classes/Copier/AssetClassCopierTest.php

https://oat-sa.atlassian.net/browse/RFE-530
https://oat-sa.atlassian.net/browse/ADF-1424
https://oat-sa.atlassian.net/browse/ADF-1425
https://oat-sa.atlassian.net/browse/ADF-1426
https://oat-sa.atlassian.net/browse/ADF-1427
Add dynamic ACL strategy to `Move to` and `Copy to` features
- Login to backoffice
- Play with the new ACL options for Items/Assets/Tests
- https://github.com/oat-sa/tao-core/pull/3776
- https://github.com/oat-sa/extension-tao-item/pull/607
- https://github.com/oat-sa/extension-tao-test/pull/438
- https://github.com/oat-sa/extension-tao-dac-simple/pull/216
- https://github.com/oat-sa/generis/pull/1036

chore: add missing dependencies for ACL strategy copy

---

migrations/Version202311171021031888_taoMediaManager.php
model/ontology/taomedia.rdf

Ticket - https://oat-sa.atlassian.net/browse/AUT-3382
Fix issue with language on edit passage properties
- fix: edit passage properties
After update and apply migrations try to edit form

fix: Neo4j - impossible to save or author passage due to language property erased when "Save" button is clicked in "Edit Passage Properties"

---

composer.json
views/js/qtiCreator/editor/ckEditor/htmlEditor.js
views/js/qtiCreator/editor/containerEditor.js
views/js/qtiCreator/editor/styleEditor/fontSizeChanger.js
views/js/qtiCreator/widgets/helpers/content.js
views/js/qtiCreator/widgets/item/Widget.js

Related: https://oat-sa.atlassian.net/browse/ADF-1579
Update lodash methods to version 4.
Documentation: https://github.com/lodash/lodash/wiki/Migrating

chore: update methods to lodash 4 verios

---

model/classes/Copier/AssetMetadataCopier.php
model/sharedStimulus/service/CopyService.php
test/unit/model/classes/Copier/AssetMetadataCopierTest.php
test/unit/model/sharedStimulus/service/CopyServiceTest.php

When copy asset we will store in rdf link to a correct source file
How to test:
1. Create class and place asset with a content in that class
2. Create new empty class
3. Copy class with new Passage and choose destination to another class.
4. Make changes in copied resource
5. Observe original asset. Make sure no changes are visible.
https://github.com/oat-sa/extension-tao-mediamanager/assets/16231681/dd583ac5-9e54-4a75-b174-bb327840f31b

fix: Copy Service now store correct link to an asset file source

---

controller/structures.xml
migrations/Version202407181259241000_taoMediaManager.php
model/MediaService.php
model/classes/Copier/AssetContentCopier.php
model/classes/ServiceProvider/MediaServiceProvider.php
model/sharedStimulus/css/service/UploadStylesheetService.php
test/unit/model/classes/Copier/AssetContentCopierTest.php

https://oat-sa.atlassian.net/browse/HKD-5
https://oat-sa.atlassian.net/browse/AUT-3754
- Allow to copy a single asset
- Fix error for GCP filesystem driver where if the stream was already closed, we should not try to close it again
- Address a bug introduced here https://github.com/oat-sa/extension-tao-mediamanager/pull/511/files where assets content are not copied if they are not a shared stimulus
- Install taoMediaManager
- Click in and asset and then copy-to
- Perform a copy and the asset must be copied
- https://github.com/oat-sa/extension-tao-deliver-connect/pull/231

feat: add possibility to copy a single asset

---

views/js/qtiCreator/component/sharedStimulusAuthoring.js

https://github.com/oat-sa/extension-tao-itemqti/pull/2585 added another required area to the area broker in order to better support the side-by-side authoring. However, other consumers that rely on this area-broker also need to declare it.
Declare the required area `editorWrapper`.
- checkout the branch: `git checkout -t origin/fix/ADF-1784/area-broker-issue`
- open a shared stimulus for authoring

fix: add the new area required by the item authoring to the area broker
