oat-sa/extension-tao-mediamanager

- manifest.php
- scripts/update/Updater.php
depends on https://github.com/oat-sa/tao-core/pull/117
> Fix modelid

- model/MediaManagerManagement.php
- scripts/install/setMediaManager.php
- test/model/MediaManagerManagementTest.php
depends on https://github.com/oat-sa/tao-core/pull/147
> Adapted to new mediaManagement interface

- model/MediaSource.php
depends on : https://github.com/oat-sa/tao-core/pull/293
> add filepath in fileinfo return

- actions/MediaManager.php
- model/MediaSource.php
- model/SharedStimulusImporter.php
- model/SharedStimulusPackageImporter.php
- views/build/grunt/sass.js
- views/css/media.css
- views/css/media.css.map
- views/js/controller/manageMedia.js
- views/scss/media.scss
- views/templates/form.tpl
depends on https://github.com/oat-sa/tao-core/pull/295
> implement previewer in edit instance view

- manifest.php
- model/FileImporter.php
- model/SharedStimulusImporter.php
- model/SharedStimulusPackageImporter.php
- scripts/update/Updater.php
depends on https://github.com/oat-sa/tao-core/pull/1104
>  Sesstion Stickyness FileUpload support

- actions/structures.xml
- manifest.php
- scripts/update/Updater.php
> Release 2.4.0

- manifest.php
- model/MediaSource.php
- scripts/update/Updater.php
> Release 2.8.1

- composer.json
- manifest.php
- model/MediaService.php
- model/MediaSource.php
- scripts/update/Updater.php
> Release 2.8.2

- manifest.php
- model/SharedStimulusPackageImporter.php
- scripts/update/Updater.php
> Release 5.0.3

- actions/MediaImport.php
- actions/MediaManager.php
- manifest.php
- scripts/update/Updater.php
Please verify the following points :
> Release 6.0.0

- controller/MediaManager.php
- manifest.php
- scripts/update/Updater.php
Please verify the following points :
> Release 8.0.0

- manifest.php
- scripts/update/Updater.php
- test/integration/model/MediaManagerBrowserTest.php
- test/integration/model/MediaServiceTest.php
- test/integration/model/MediaSourceTest.php
- test/integration/model/SharedStimulusImporterTest.php
- test/integration/model/SharedStimulusPackageImporterTest.php
related to: https://oat-sa.atlassian.net/browse/TDR-1
depends on: https://github.com/oat-sa/generis/pull/751
Upgrade to phpunit8
> Feature/tdr 1/phpunit8 upgrade

- manifest.php
- model/MediaService.php
- scripts/update/Updater.php
Please verify the following points :
> Release 9.2.1

- manifest.php
- model/MediaSource.php
- scripts/update/Updater.php
Please verify the following points :
> Release 9.3.0

- manifest.php
Update tao dependency version on manifest
> Update tao dependency version on manifest

- manifest.php
> update version operator

- scripts/update/Updater.php
Update version diverging from manifest version
> Update version diverging from manifest version

- controller/SharedStimulus.php
- controller/structures.xml
- doc/taoMediaManagerApi.yml
- manifest.php
- model/sharedStimulus/CreateCommand.php
- model/sharedStimulus/FindQuery.php
- model/sharedStimulus/SharedStimulus.php
- model/sharedStimulus/factory/CommandFactory.php
- model/sharedStimulus/factory/QueryFactory.php
- model/sharedStimulus/repository/SharedStimulusRepository.php
- model/sharedStimulus/service/CreateService.php
- model/sharedStimulus/service/RetrieveService.php
- scripts/update/Updater.php
- test/unit/model/sharedStimulus/factory/CommandFactoryTest.php
- test/unit/model/sharedStimulus/factory/QueryFactoryTest.php
- test/unit/model/sharedStimulus/repository/SharedStimulusRepositoryTest.php
- test/unit/model/sharedStimulus/service/CreateServiceTest.php
https://oat-sa.atlassian.net/browse/NEX-964
Introduce new endpoint to get shared stimulus.
p.s: Tests are being finished.
> adding new retrieval endpoint

- doc/taoMediaManagerApi.yml
- model/sharedStimulus/FindQuery.php
- model/sharedStimulus/SharedStimulus.php
- model/sharedStimulus/factory/CommandFactory.php
- model/sharedStimulus/repository/SharedStimulusRepository.php
- model/sharedStimulus/repository/SharedStimulusRepositoryInterface.php
- model/sharedStimulus/service/CreateService.php
Remove RDF language for external interfaces
> remove RDF reference

- model/sharedStimulus/parser/JsonQtiAttributeParser.php
- model/sharedStimulus/service/CreateService.php
- test/integration/model/JsonQtiAttributeParserTest.php
- Fix to allow creation with sharedstimulus with empty body
> Allow empty media

- views/js/controller/actions.js
- views/js/controller/authoring.js
- views/js/qtiCreator/component/sharedStimulusAuthoring.js
- views/js/qtiCreator/component/tpl/sharedStimulusAuthoring.tpl
- views/js/qtiCreator/helper/createDummyItemData.js
- views/js/qtiCreator/helper/xmlRenderer.js
- views/js/qtiCreator/sharedStimulusCreator.js
- views/js/qtiCreator/widgets/item/Widget.js
- views/js/qtiCreator/widgets/item/states/Active.js
- views/js/qtiXmlRenderer/renderers/Item.js
- views/js/qtiXmlRenderer/renderers/Renderer.js
- views/js/qtiXmlRenderer/renderers/config.js
- views/js/qtiXmlRenderer/tpl/item.tpl
Related to: https://oat-sa.atlassian.net/browse/UNO-321
Implemented save functionality for the passage(Shared stimulus) on the passage Authoring page
How to test:
1. go to the Assets page
2. create a new passage or open existing one to Authoring
3. edit passage - add text, table, tooltip, etc
4. save a passage
> UNO-321 save shared stimulus

- views/js/controller/actions.js
Related to: https://oat-sa.atlassian.net/browse/NEX-968
Fix request for creation new Shared Stimulus
> Fix NEX-968 send classId in JSON

- views/js/controller/actions.js
- views/js/qtiCreator/sharedStimulusCreator.js
Related to: https://oat-sa.atlassian.net/browse/NEX-968
Fix request `delete` Shared Stimulus
> Fix NEX-968 use core/request

- manifest.php
- model/ZipExporter.php
- model/export/service/MediaResourcePreparer.php
- scripts/install/SetMediaManager.php
- scripts/update/Updater.php
- test/integration/model/export/service/MediaResourcePreparerTest.php
https://oat-sa.atlassian.net/browse/NEX-1202
depends on
https://github.com/oat-sa/extension-tao-itemqti/pull/1467
> Fix/nex 1202/export shared stimulus with item

- manifest.php
- scripts/update/Updater.php
- views/build/grunt/bundle.js
- views/build/grunt/paths.json
Fixed taomediamanagerbundle task
How to test:
`cd tao/views/build`
`npm i`
`npx grunt taomediamanagerbundle`
> add dependency for bundle

- manifest.php
- scripts/update/Updater.php
- views/js/controller/actions.js
**Related to**
https://oat-sa.atlassian.net/browse/NEX-1258
**Description**
Change param sent to delete API to the old way because that endpoint don't suffer any change
**AC**
> Fix NEX-1258 - Language not returned in shared stimulus

- controller/MediaManager.php
- controller/SharedStimulus.php
- manifest.php
- model/MediaService.php
- model/MediaSource.php
- model/fileManagement/FileSourceSerializer.php
- model/fileManagement/FileSourceUnserializer.php
- model/sharedStimulus/repository/SharedStimulusRepository.php
- test/unit/model/sharedStimulus/repository/SharedStimulusRepositoryTest.php
fix bug about revision handling,
tickets : 
https://oat-sa.atlassian.net/browse/NEX-1419
https://oat-sa.atlassian.net/browse/NEX-1418
https://oat-sa.atlassian.net/browse/NEX-1439
> Fix/nex 1419/fixing shared stimulus revision

- model/relation/task/ItemToMediaRelationshipMigrationTask.php
https://github.com/oat-sa/extension-tao-itemqti/pull/1492
> Feature/nex 1135/migration refactoring

- model/relation/service/AbstractRdsSearcher.php
- model/relation/service/ItemToMediaRdsSearcher.php
- model/relation/service/MediaToMediaRdsSearcher.php
- model/relation/task/ItemToMediaRelationMigrationTask.php
- model/relation/task/ItemToMediaUnitProcessor.php
- model/relation/task/MediaToMediaRelationMigrationTask.php
- model/relation/task/MediaToMediaUnitProcessor.php
- test/unit/model/relation/task/ItemToMediaRelationMigrationTaskTest.php
- test/unit/model/relation/task/ItemToMediaUnitProcessorTest.php
- test/unit/model/relation/task/MediaToMediaUnitProcessorTest.php
This PR is a draft proposal that I would like to propose in order to improve the media item migration command code base. 
Implementing interfaces introduced in `tao-core` extension [PR](https://github.com/oat-sa/tao-core/pull/2622).
- `model/relation/service/MediaToMediaRdsSearcher.php`
- `model/relation/service/ItemToMediaRdsSearcher.php`
Replacing old interfaces with those introduced in `tao-core` [PR](https://github.com/oat-sa/tao-core/pull/2622)
> Code refactor

- manifest.php
- model/sharedStimulus/parser/JsonQtiAttributeParser.php
Pull request summary
Related to : https://oat-sa.atlassian.net/browse/UNO-628
Added possibility to work with huge xml files
Companion PR:
> Fix/uno 628/huge xml files

- controller/MediaManager.php
- manifest.php
https://oat-sa.atlassian.net/browse/NEX-1816
Depends on
> svgz images support

- controller/MediaRelations.php
- doc/taoMediaManagerApi.yml
- manifest.php
- migrations/Version202010301232112234_taoMediaManager.php
- model/exception/ComplexSearchLimitException.php
- model/relation/MediaRelation.php
- model/relation/MediaRelationCollection.php
- model/relation/MediaRelationService.php
- model/relation/repository/query/FindAllQuery.php
- model/relation/repository/rdf/RdfMediaRelationRepository.php
- scripts/install/SetMediaManager.php
- test/unit/model/relation/MediaRelationTest.php
- views/js/controller/actions.js
- Use tao-core base classes for relation management
- Deprecate old class / methods
ATTENTION!!! Build breaks because classes on tao-core were not merged yet.
https://oat-sa.atlassian.net/browse/CON-12
> use tao-core base classes to relation control

- manifest.php
- views/js/qtiCreator/tpl/forms/static/text.tpl
- views/js/qtiCreator/widgets/static/text/states/Active.js
Related to: https://oat-sa.atlassian.net/browse/NEX-2170
Fix regression from https://github.com/oat-sa/extension-tao-itemqti/pull/1570
How to test:
- go to Assets authoring tool
- Select shared stimulus
- no Scrolling options
> [Fix] NEX 2170 - Remove regression

- manifest.php
- model/MediaSource.php
- test/integration/model/MediaSourceTest.php
Cherry pick of https://github.com/oat-sa/extension-tao-mediamanager/pull/239
https://oat-sa.atlassian.net/browse/CON-111
> Fix/con 111/perfomance improvement

- manifest.php
- model/MediaSource.php
- scripts/update/Updater.php
Added forgotten lines into updater ( missed as we moved  for a newer migration in modern versions) 
No functional changes  introduced.
> Hotfix/con 111/reduced queries to rds

- manifest.php
- model/MediaSource.php
https://oat-sa.atlassian.net/browse/CON-313
> Support pagination for resources loading

- manifest.php
- views/js/qtiCreator/widgets/static/object/states/Active.js
Related to: https://oat-sa.atlassian.net/browse/CON-30
https://github.com/oat-sa/tao-core/pull/2780
https://github.com/oat-sa/tao-core-ui-fe/pull/243
https://github.com/oat-sa/extension-tao-test-preview-ui-loader/pull/17
https://github.com/oat-sa/extension-tao-itemqti/pull/1610
https://github.com/oat-sa/tao-item-runner-qti-fe/pull/140
Support video responsive width in Assets Authoring.
How to test:
- go to Assets Authoring
- add video
- try to scale
- check scale in preview
> Feature/CON-30/support responsive video in Assets Authoring

- manifest.php
- model/fileManagement/FlySystemManagement.php
https://oat-sa.atlassian.net/browse/CON-287
Fixes issue with asset resource disposal after uploading to the cloud storage 
Is the must for https://github.com/oat-sa/lib-generis-gcp/pull/4
> Fix/con 287/failsafe resource disposal

- composer.json
- controller/MediaExport.php
- controller/MediaImport.php
- controller/MediaManager.php
- controller/SharedStimulus.php
- controller/structures.xml
- manifest.php
- migrations/Version202104131232112245_taoMediaManager.php
- model/ZipExporter.php
- model/editInstanceForm.php
> Release 12.2.0

- composer.json
- controller/SharedStimulus.php
- doc/taoMediaManagerApi.yml
- model/ZipExporter.php
- test/integration/model/MediaServiceTest.php
- test/unit/model/relation/task/MediaToMediaUnitProcessorTest.php
- views/js/controller/actions.js
Fix ACL permissions to create passage when selecting an asset
https://oat-sa.atlassian.net/browse/ADF-311
Can be tested on http://test-gabriel.playground.kitchen.it.taocloud.org:42221/ 
admin/admin
Related PRs:
> Fix ACL permissions to create passage when selecting the resource

- model/ZipExporter.php
Revert temporarily ACL for UDIR
https://oat-sa.atlassian.net/browse/ADF-340
> fix: remove permission validator

- model/ZipExporter.php
> Release 12.2.2

- composer.json
- model/MediaSource.php
- test/integration/model/MediaSourceTest.php
Apply ACL for assets on authoring
https://oat-sa.atlassian.net/browse/ADF-271
> ACL for assets authoring

- composer.json
- model/MediaSource.php
- test/integration/model/MediaSourceTest.php
> Release 12.3.0

- model/MediaSource.php
https://oat-sa.atlassian.net/browse/ADF-237
> feat: clear tmp files

- model/MediaSource.php
> Release 12.4.0

- views/js/qtiCreator/widgets/static/img/Widget.js
- views/js/qtiCreator/widgets/static/img/states/Active.js
This is alternative to https://github.com/oat-sa/extension-tao-mediamanager/pull/240
**Jira**
https://oat-sa.atlassian.net/browse/ADF-39
**Other PRs**
https://github.com/oat-sa/tao-core-ui-fe/pull/302
https://github.com/oat-sa/extension-tao-itemqti/pull/1761
https://github.com/oat-sa/tao-core/pull/2936
https://github.com/oat-sa/extension-tao-devtools/pull/188
**Environment**
Deployed to the playground, the link is in the ticket
Also created ticket for tech debt in order to push and close this one on time https://oat-sa.atlassian.net/browse/ADF-433
> [Feature] ADF-39 - Text wrap pictures

- composer.json
- views/js/qtiCreator/widgets/static/img/states/Active.js
Reverts oat-sa/extension-tao-mediamanager#280
> Revert "[Refactor] ADF-433 Reuse logic for image active state in qtiItem and mediaManager"

- views/cypress/tests/assetss-page.spec.js
- views/cypress/utils/urls.js
> Release 12.7.0

- controller/MediaManager.php
- controller/structures.xml
Enable action "Move to" to asset resources
[AUT-784](https://oat-sa.atlassian.net/browse/AUT-784)
> add actions for moving assets

- controller/MediaManager.php
- controller/structures.xml
> Release 12.8.0

- controller/MediaManager.php
- controller/structures.xml
https://oat-sa.atlassian.net/browse/AUT-198
[backport/feat/AUT-784/enable-action-move-on-asset-resource 5f647a7] feat: add actions for moving assets
Date: Thu Jul 15 17:13:07 2021 +0200
2 files changed, 12 insertions(+)
> feat: add actions for moving assets

- controller/MediaImport.php
> Release 12.8.1

- composer.json
- controller/MediaManager.php
- controller/structures.xml
- manifest.php
- migrations/Version202107161250081888_taoMediaManager.php
- migrations/Version202107261845541888_taoMediaManager.php
- model/mapper/MediaSourcePermissionsMapper.php
- model/ontology/taomedia.rdf
- model/user/TaoAssetRoles.php
- views/templates/form.tpl
> Release 12.10.0

- views/cypress/tests/assets.spec.js
- views/cypress/utils/selectors.js
> Release 12.11.0

- composer.json
- manifest.php
- migrations/Version202108091845541888_taoMediaManager.php
- model/mapper/MediaSourcePermissionsMapper.php
- scripts/install/SetRolesPermissions.php
- test/unit/model/mapper/MediaSourcePermissionsMapperTest.php
feat: add permissions for upload and delete separately
https://oat-sa.atlassian.net/browse/ADF-573
> feat: add permissions for upload and delete separately

- composer.json
- manifest.php
- migrations/Version202108091845541888_taoMediaManager.php
- model/mapper/MediaSourcePermissionsMapper.php
- test/unit/model/mapper/MediaSourcePermissionsMapperTest.php
> Release 12.12.0

- views/js/qtiCreator/plugins/menu/preview.js
- views/js/qtiCreator/plugins/menu/save.js
- views/js/qtiCreator/plugins/navigation/back.js
**Ticket:** https://oat-sa.atlassian.net/browse/AUT-949
**How to test:**
- Go to Assets authoring
- Check that Manage Assets, Save, Preview buttons have data-testid attrs
> feat: add data-testid attrs on the asset authoring page

- composer.json
- migrations/Version202108271508361888_taoMediaManager.php
- model/classes/user/TaoAssetRoles.php
- model/mapper/MediaSourcePermissionsMapper.php
- test/unit/model/mapper/MediaSourcePermissionsMapperTest.php
> Release 12.13.1

- views/cypress/tests/assets-page.spec.js
- views/cypress/tests/assets.spec.js
> Release 12.13.2

- composer.json
- controller/SharedStimulus.php
- manifest.php
- migrations/Version202109081901591888_taoMediaManager.php
- scripts/install/SetupMiddlewares.php
> Release 12.13.3

- views/cypress/tests/assets.spec.js
> Release 12.13.4

- views/cypress/tests/assets-page.spec.js
- views/cypress/tests/assets.spec.js
**Ticket**
https://oat-sa.atlassian.net/browse/ADF-634
> [FE][e2e testing] Group before() command in item, test and assets spec.js

- views/cypress/tests/assets-page.spec.js
- views/cypress/tests/assets.spec.js
> Release 12.13.5

- views/cypress/utils/selectors.js
> Release 12.13.6

- views/cypress/tests/assets.spec.js
- views/cypress/utils/add-A-block-interaction-asset.js
> Release 12.18.0

- manifest.php
- migrations/Version202111151250521888_taoMediaManager.php
- model/MediaSource.php
- model/ZipExporter.php
- model/export/service/MediaResourcePreparer.php
- model/export/service/MediaResourcePreparerInterface.php
- scripts/install/RegisterMediaResourcePreparer.php
> Release 12.20.0

- model/sharedStimulus/parser/JsonQtiAttributeParser.php
- test/integration/model/JsonQtiAttributeParserTest.php
- test/unit/model/sharedStimulus/parser/JsonQtiAttributeParserTest.php
This implementation is intended to solve the issue: https://oat-sa.atlassian.net/browse/AUT-1505
Please check the steps to reproduce to see the issue.
> [AUT-1505] Fix lang attribute is replaced by class attribute #354

- model/sharedStimulus/parser/JsonQtiAttributeParser.php
- test/integration/model/JsonQtiAttributeParserTest.php
- test/unit/model/sharedStimulus/parser/JsonQtiAttributeParserTest.php
This implementation is intended to solve the issue: https://oat-sa.atlassian.net/browse/AUT-1505
Please check the steps to reproduce to see the issue.
> [Backport][AUT-1505] Fix lang attribute is replaced by class attribute #354

- model/sharedStimulus/parser/JsonQtiAttributeParser.php
- test/integration/model/JsonQtiAttributeParserTest.php
- test/unit/model/sharedStimulus/parser/JsonQtiAttributeParserTest.php
> Release 12.20.1

- model/sharedStimulus/service/PatchService.php
- model/sharedStimulus/service/StoreService.php
- test/integration/model/SharedStimulusImporterTest.php
> Release 12.20.2

- views/cypress/tests/add-asset-passage-to-interaction.spec.js
- views/cypress/utils/check-read-only.js
- views/cypress/utils/import-selected-asset.js
- views/cypress/utils/resource-manager.js
- views/cypress/utils/selectors.js
> Release 12.21.0

- migrations/Version202112230835581888_taoMediaManager.php
- scripts/ReplaceSharedStimulusMedia.php
This is cherry-pick from this script fixing rich passages: https://github.com/oat-sa/extension-tao-mediamanager/pull/366 already checked on customer alive environment
plus a migration which will execute the script on taoUpdate
> Fix/aut 1620/add migration script fixing older passages paths

- migrations/Version202112230835581888_taoMediaManager.php
- scripts/ReplaceSharedStimulusMedia.php
> Release 12.21.1

- views/cypress/tests/add-asset-passage-to-interaction.spec.js
- views/cypress/utils/check-read-only.js
Related to: https://oat-sa.atlassian.net/browse/AUT-973
Stabilize e2e tests
> fix/AUT-973/stabilize e2e test: isChoice issue

- views/cypress/tests/add-asset-passage-to-interaction.spec.js
- views/cypress/utils/check-read-only.js
> Release 12.21.2

- views/js/qtiCreator/editor/ckEditor/htmlEditor.js
Related to: https://oat-sa.atlassian.net/browse/AUT-114
Add featureFlag to disable table cell alignment
Cherry pick of https://github.com/oat-sa/extension-tao-mediamanager/pull/376/commits/bfe7ca92a9c0f9cfae27042cb760dc872ddf5e1b
> feat: add feature flag disableCellAlignment

- migrations/Version202112230835581888_taoMediaManager.php
- scripts/ReplaceSharedStimulusMedia.php
* `ReplaceSharedStimulusMedia` script was changed from simple script to `ScriptAction`
* `ReplaceSharedStimulusMedia` script refactored:
* Reduce multi-level if-statements
* Store some function calls in variables
* Added file existence check
* Wrapped into `try-catch` block
* Added logs and reports
* If link was not updated - new file and directory will be deleted
> Refactor: cover replacement script with checks

- migrations/Version202112230835581888_taoMediaManager.php
- scripts/ReplaceSharedStimulusMedia.php
> Release 12.25.1

- manifest.php
- migrations/Version202111220850431888_taoMediaManager.php
- model/SharedStimulusPackageImporter.php
- model/sharedStimulus/encoder/SharedStimulusMediaEncoder.php
- model/sharedStimulus/encoder/SharedStimulusMediaEncoderInterface.php
- scripts/install/RegisterSharedStimulusMediaEncoder.php
- test/integration/model/SharedStimulusPackageImporterTest.php
> Release 12.25.2

- migrations/Version202112230835581888_taoMediaManager.php
- scripts/ReplaceSharedStimulusMedia.php
Backport of https://github.com/oat-sa/extension-tao-mediamanager/pull/385 and https://github.com/oat-sa/extension-tao-mediamanager/pull/393 for `tao-community` March release
> [Backport] REL-709 shared stimulus migration

- .github/workflows/continuous-integration.yaml
- README.md
- composer.json
- test/unit/model/Specification/MediaClassSpecificationTest.php
This PR aims to integrate the extension with a new CI pipeline defined by https://github.com/oat-sa/tao-extension-ci-action
⚠️ It is expected that PHP > 7.4 pipeline fail ⚠️
- ci: add a CI action
- docs: add a codecov badge to README.md
> Feature ADF-1102 CI pipeline

- composer.json
- views/js/qtiCreator/helper/ckConfigurator.js
Related to https://oat-sa.atlassian.net/browse/AUT-2473
- Configure the HR plugin in passage authoring
**Requires**
- https://github.com/oat-sa/tao-core-shared-libs-fe/pull/24
- https://github.com/oat-sa/tao-core-ui-fe/pull/467
- https://github.com/oat-sa/tao-core/pull/3570
**TODO**
- along with companion PRs: add, remove, etc. horizontal lines in the passage authoring. Try to export/import created passages
> Configure the hr plugin for passage authoring

- model/classes/ServiceProvider/MediaServiceProvider.php
**Associated Jira issue:** [ADF-1148](https://oat-sa.atlassian.net/browse/ADF-1148)
Parent PR: https://github.com/oat-sa/tao-core/pull/3591
> fix: Register copiers in the DI container using tags

- model/classes/ServiceProvider/MediaServiceProvider.php
> Release 12.31.1

- model/classes/ServiceProvider/MediaServiceProvider.php
**Associated Jira issue:** [ADF-1148](https://oat-sa.atlassian.net/browse/ADF-1148)
> fix: Register copiers in the DI container using tags (backport)

- .github/workflows/continuous-integration.yaml
- composer.json
- model/sharedStimulus/SharedStimulus.php
> Release 12.31.4

- model/sharedStimulus/service/CopyService.php
- test/unit/model/sharedStimulus/service/CopyServiceTest.php
> Release 12.33.1

- views/js/previewer/proxy/qtiSharedStimulusItem.js
- views/js/qtiCreator/component/tpl/sharedStimulusAuthoring.tpl
- views/js/qtiCreator/editor/styleEditor/colorSelector.js
- views/js/qtiCreator/editor/styleEditor/fontSelector.js
- views/js/qtiCreator/editor/styleEditor/fontSizeChanger.js
- views/js/qtiCreator/editor/styleEditor/styleEditor.js
- views/js/qtiCreator/helper/formatStyles.js
- views/js/qtiCreator/helper/sharedStimulusLoader.js
- views/js/richPassage/helpers.js
- views/js/richPassage/xincludeRendererAddStyles.js
Backport of https://github.com/oat-sa/extension-tao-mediamanager/pull/435 to [tao-community](https://github.com/oat-sa/tao-community/blob/2022.10.5/composer.json#L57) on Udir October release.
> Hotfix/aut 2694/hide styles with no class name

- composer.json
Update QTI lib to support ruby tag
> chore: update qti lib

- composer.json
> Release 12.33.5

- composer.json
- views/js/qtiCreator/helper/ckConfigurator.js
Related to: https://oat-sa.atlassian.net/browse/AUT-2651
Enable ruby plugin by option (additional condition by feature flag will be checked in )
How to test see https://github.com/oat-sa/tao-core/pull/3644
> feat: use furiganaPlugin option

- composer.json
- model/classes/Copier/AssetClassCopier.php
- model/classes/ServiceProvider/MediaServiceProvider.php
- test/unit/model/classes/Copier/AssetClassCopierTest.php
> Release 12.34.4

- manifest.php
- migrations/Version202306061259241888_taoMediaManager.php
- model/ontology/taomedia.rdf
- model/user/TaoAssetRoles.php
- scripts/install/AddAssetClassEditorRolePermission.php
Add a role that will allow the user to edit the asset class name
How to test:
- Create a user with `AddAssetClassEditorRole`
- Login to new user
- Open Asset tab
- Create new class
- Make sure you can edit class name
> feat: add new role that will allow editing asset class name

- crowdin.yml
- manifest.php
- migrations/Version202306061259241888_taoMediaManager.php
- model/ontology/taomedia.rdf
- model/user/TaoAssetRoles.php
- scripts/install/AddAssetClassEditorRolePermission.php
> Release 12.36.0

- composer.json
- model/AssetDeleter.php
- model/classes/ServiceProvider/MediaServiceProvider.php
- model/relation/event/processor/ItemRemovedEventProcessor.php
- model/relation/repository/rdf/RdfMediaRelationRepository.php
- test/unit/model/AssetDeleterTest.php
> Release 12.37.0

- scripts/MoveResources.php
Ticket: https://oat-sa.atlassian.net/browse/PISA25-557
- Create script for moving item assets to given class
Run script in console : php index.php 'oat\taoMediaManager\scripts\MoveResource' [--id] [--namePattern] [--destinationClass]
It can move resource by its id or name pattern, you must specify destination class uri.
Demo:
Moving classes: 
https://github.com/oat-sa/extension-tao-mediamanager/assets/118974926/56324f62-c691-4343-a86d-3610962b3b0b
> feature: script for moving item assets to given class

- model/export/service/MediaResourcePreparer.php
Ticket: https://oat-sa.atlassian.net/browse/AUT-4012
- Handled the case when no file received
- The export will fail if no file received
> fix: fail export when no file contents received
